import { categories } from './categories';
const { womens, mens, kids, sale } = categories;
export const productsData = [
	{
		id: 1,
		name: 'Black Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/ahmed-ghanem-21F4hU6YPPM-unsplash.jpg'),
		price: 1599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 2,
		name: 'Cream T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/alex-haigh-fEt6Wd4t4j0-unsplash.jpg'),
		price: 499,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, sale],
	},
	{
		id: 3,
		name: 'Green Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/atikh-bana-_KaMTEmJnxY-unsplash.jpg'),
		price: 349,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens, sale],
	},
	{
		id: 4,
		name: 'White T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/bao-bao-GREEBEtyR9Y-unsplash.jpg'),
		price: 1599,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens],
	},
	{
		id: 5,
		name: 'Colourful Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/danie-franco-NV_IPwv0Saw-unsplash.jpg'),
		price: 1199,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids],
	},
	{
		id: 6,
		name: 'Blue Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/darko-mitev-c5t_j1zlk1Y-unsplash.jpg'),
		price: 1399,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 7,
		name: 'Silver Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/enis-yavuz-oD3X-e4L2ac-unsplash.jpg'),
		price: 799,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids, sale],
	},
	{
		id: 8,
		name: 'Green Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/eugenivy_now-CaezTVrEkdg-unsplash.jpg'),
		price: 3299,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids],
	},
	{
		id: 9,
		name: 'Black T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/faith-yarn-Wr0TpKqf26s-unsplash.jpg'),
		price: 2199,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, kids],
	},
	{
		id: 10,
		name: 'Marron Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/freestocks-_3Q3tsJ01nc-unsplash.jpg'),
		price: 2599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 11,
		name: 'Red Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/holger-ochoa-9W9obie_3lM-unsplash.jpg'),
		price: 2299,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 12,
		name: 'Blue Suit',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/hunters-race-MYbhN8KaaEc-unsplash.jpg'),
		price: 3599,
		quantity: 1,
		type: 'Suit',
		size: 'M',
		category: [mens],
	},
	{
		id: 13,
		name: 'Light Blue Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/james-lewis-ohiyigDmlYc-unsplash.jpg'),
		price: 2599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 14,
		name: 'Red T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/katsiaryna-endruszkiewicz-BteCp6aq4GI-unsplash.jpg'),
		price: 699,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [womens, kids, sale],
	},
	{
		id: 15,
		name: 'Red Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/kayan-baby-kPXq-jxhMkk-unsplash.jpg'),
		price: 1699,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids],
	},
	{
		id: 16,
		name: 'Marron Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/khaled-ghareeb--NyPn9up_7o-unsplash.jpg'),
		price: 2699,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 17,
		name: 'Black Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/knight-duong-77iyep3uIjg-unsplash.jpg'),
		price: 1899,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 18,
		name: 'Pink Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/luobulinka-FO4mQZi1c0M-unsplash.jpg'),
		price: 1499,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 19,
		name: 'Green Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/mariabeatrice-alonzi-VyI0GBHSsJ8-unsplash.jpg'),
		price: 1899,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 20,
		name: 'Pink T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/marlon-alves-A0mSSCEVh9A-unsplash.jpg'),
		price: 899,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, kids, sale],
	},
	{
		id: 21,
		name: 'Black T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/meysam-jarahkar-NMYG69BG_Jg-unsplash.jpg'),
		price: 799,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, sale],
	},
	{
		id: 22,
		name: 'Black Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/mohamad-khosravi-4fkUAduhoSY-unsplash.jpg'),
		price: 1299,
		quantity: 1,
		type: 'Shirt',
		size: 'M',
		category: [mens],
	},
	{
		id: 23,
		name: 'Black Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/nassim-boughazi-dodzmVtjoKs-unsplash.jpg'),
		price: 2299,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 24,
		name: 'Yellow Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/nikhil-uttam-QrOdhsMAQw8-unsplash.jpg'),
		price: 1699,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 25,
		name: 'Orange Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/nikolay-hristov-r28YZ4376hU-unsplash.jpg'),
		price: 1799,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens, sale],
	},
	{
		id: 26,
		name: 'Blue Pink Set',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/olga-kisiel-konopka-IW9flBDpy2I-unsplash.jpg'),
		price: 2499,
		quantity: 1,
		type: 'Set',
		size: 'M',
		category: [kids, sale],
	},
	{
		id: 27,
		name: 'Black Yellow Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/phil-monte-4V4t0JcOM5E-unsplash.jpg'),
		price: 1199,
		quantity: 1,
		type: 'Shirt',
		size: 'M',
		category: [mens, sale],
	},
	{
		id: 28,
		name: 'Red Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/r-n-tyfqOL1FAQc-unsplash.jpg'),
		price: 3099,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 29,
		name: 'White Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/raamin-ka-uR51HXLO7G0-unsplash.jpg'),
		price: 2399,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 30,
		name: 'Olive Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/raquel-gambin-kS3YkVtf85U-unsplash.jpg'),
		price: 1299,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens, sale],
	},
	{
		id: 31,
		name: 'Yellow Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/rendy-novantino-_jd8I6yBWM4-unsplash.jpg'),
		price: 2399,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 32,
		name: 'White Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/reza-delkhosh-iRAOJYtPHZE-unsplash.jpg'),
		price: 2599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 33,
		name: 'White T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/rock-staar-2XcbGfYShfk-unsplash.jpg'),
		price: 899,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, sale],
	},
	{
		id: 34,
		name: 'Blue Jacket',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/roland-hechanova-nutRT2AD580-unsplash.jpg'),
		price: 1999,
		quantity: 1,
		type: 'Jacket',
		size: 'M',
		category: [womens],
	},
	{
		id: 35,
		name: 'Black T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/ryan-hoffman-u6n1HrW0sdQ-unsplash.jpg'),
		price: 599,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, womens, kids, sale],
	},
	{
		id: 36,
		name: 'White T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/sahil-moosa-m1MRYp556Ew-unsplash.jpg'),
		price: 499,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, kids, sale],
	},
	{
		id: 37,
		name: 'Jeans T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/santhosh-kumar-RqYTuWkTdEs-unsplash.jpg'),
		price: 899,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [womens, kids, sale],
	},
	{
		id: 38,
		name: 'White T-Shirt',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/sincerely-media-9ShY-Tq70Mc-unsplash.jpg'),
		price: 799,
		quantity: 1,
		type: 'T-Shirt',
		size: 'M',
		category: [mens, kids, sale],
	},
	{
		id: 39,
		name: 'Red Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/suheyl-burak-p7I07kuPSyU-unsplash.jpg'),
		price: 2799,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 40,
		name: 'Peach Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/tamara-bellis-mNZ-GvOQUUY-unsplash.jpg'),
		price: 1399,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 41,
		name: 'Blue Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/travis-grossen-vetYLH9Rnmg-unsplash.jpg'),
		price: 1599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids],
	},
	{
		id: 42,
		name: 'Black Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/valerie-elash-gsKdPcIyeGg-unsplash.jpg'),
		price: 2599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 43,
		name: 'Strip Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/vitaliy-zalishchyker-0uSAeOByv-0-unsplash.jpg'),
		price: 1599,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [kids],
	},
	{
		id: 44,
		name: 'White Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/yasu-shots-_y6hMz1pJC0-unsplash.jpg'),
		price: 2299,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
	{
		id: 45,
		name: 'Golden Dress',
		description:
			'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nisl eget consequat aliquam, nulla sapien consectetur ex, quis mollis ex lorem sit amet urna. Donec auctor, velit vitae ultrices ultrices, nisl justo luctus nunc, in sollicitudin dolor nunc vitae nisl. Sed vitae nunc id nisl ultrices luctus. Sed vitae nunc id nisl ultrices luctus.',
		imgSource: require('../assets/yves-monrique-LR99Ho2eIec-unsplash.jpg'),
		price: 1699,
		quantity: 1,
		type: 'Dress',
		size: 'M',
		category: [womens],
	},
];

// const result = productsData
// 	.reduce((prev, curr, index, arr) => {
// 		return prev + curr.price * curr.quantity;
// 	}, 0)
// 	.toFixed(2);

// console.log(result);
